#1175 Renaming libs to lib when calling export portable
jbangdev/jbang pull request #1176
Opened 2021-12-31 14:29 UTC by nandorholozsnyak

- Option to put the lib folder into the final jar

2022-01-01 00:28 UTC, quintesse commented
You're trying to create an "uber jar" that contains everything, right? But AFAIK doing it like this isn't correct. Did you try the resulting jar file on a clean system? I'm guessing it's really still obtaining them from your local file system. Also see: https://imagej.net/develop/uber-jars

2022-01-01 00:35 UTC, quintesse commented
Aha I just read https://github.com/jbangdev/jbang/issues/1175 so I understand what you're trying to do, but I don't think we should add an option for something that only works for AWS. So either we add a proper `export uberjar` option or I'd suggest you create a simple script that would turn the result from `export portable` into something that can be used with AWS.

2022-01-01 12:17 UTC, maxandersen commented on src/main/java/dev/jbang/cli/Export.java
> +            if (exportMixin.packageLibFolder) {
are you sure this is doing what you think it is ? just adding folder to the jar doesn't make it visible to the standard java class loader.

2022-01-01 12:19 UTC, maxandersen reviewed
the change of `libs` to `lib` is fine but lets not mix that up with trying to make an uber-jar . The approach of adding lib/ folder to the jar I doubt works.

2022-01-01 12:19 UTC, maxandersen requested changes
see comments

2022-01-01 12:52 UTC, nandorholozsnyak commented on src/main/java/dev/jbang/cli/Export.java
> +            if (exportMixin.packageLibFolder) {
That is true, you need a special class loader for it like what Spring Boot has (or at least I read about it). In this case I think it would be better to provide a new command which explicitely tells that it is going to create a .zip file that could be used on AWS Lambda. 
I think that would be cleaner, this first attempt was just a PoC. 

What do you think about a new command or new flags that will create a .zip with the lib folder and not the jar with the lib folder?

2022-01-01 21:04 UTC, nandorholozsnyak commented
@maxandersen I just deleted the packaging of the lib folder and made some changes to the documentation as well.
I can imagine it is going to cause some sort of backward compatibility issues if developers are expecting the existence the `lib` folder.

On the other topic, what would be the best way to implement this "zipping" mechanism with the `lib` folder? New command, or export command with --aws-function option ?

2022-01-01 23:31 UTC, quintesse commented
> On the other topic, what would be the best way to implement this "zipping" mechanism with the lib folder? New command, or export command with --aws-function option ?

My personal preference would be a simple `--zip` option to the `export portable` option, because that's basically what it does, the entire rest of the procedure is the same, except for the part where at the end a zip is created.

Personally I would stay away from AWS-specific naming unless there really is no way the export could be used by anything else but AWS. (And if that were the case I'd doubt the usefulness of adding such specific exports to the core Jbang code)

2022-01-01 23:47 UTC, nandorholozsnyak commented
> > On the other topic, what would be the best way to implement this "zipping" mechanism with the lib folder? New command, or export command with --aws-function option ?
> 
> My personal preference would be a simple `--zip` option to the `export portable` option, because that's basically what it does, the entire rest of the procedure is the same, except for the part where at the end a zip is created.
> 
> Personally I would stay away from AWS-specific naming unless there really is no way the export could be used by anything else but AWS. (And if that were the case I'd doubt the usefulness of adding such specific exports to the core Jbang code)

Okay, I can totally understand it, what you wrote earlier about creating a simple post processing on the end user end is still a good workaround. If the `--zip` gets green light then I will implement it on another branch.

2022-01-02 06:59 UTC, maxandersen approved these changes

2022-01-02 07:00 UTC, maxandersen commented
@all-contributors please add @nandorholozsnyak  for code

2022-01-02 07:34 UTC, merged