feat: Catalog templates with property list
jbangdev/jbang pull request #1205
Opened 2022-01-18 23:02 UTC by nandorholozsnyak

- Property can have description and default value
- Adding multiple property at the same time with a specific format
- Listing templates returns the list of the template properties too

Associated issue: https://github.com/jbangdev/jbang/issues/1203

2022-01-19 10:13 UTC, quintesse requested changes
Looks good! Just needs a couple of minor changes.
It also needs tests and changes to the docs :-)

2022-01-19 10:13 UTC, quintesse commented on src/main/java/dev/jbang/catalog/Template.java
> +	public Template(Map<String, String> fileRefs, String description, Catalog catalog,
This is not wrong of course, but could you change the order a bit? The `catalog` is meant to be the last argument in the list.

2022-01-19 10:13 UTC, quintesse commented on src/main/java/dev/jbang/catalog/Catalog.java
> +				new Template(t.fileRefs, t.description, this, new HashMap<>())));
Use `Collections.emptyMap()` here.

2022-01-19 10:13 UTC, quintesse commented on src/main/java/dev/jbang/catalog/CatalogUtil.java
> +import java.util.*;
Make sure you run `./gradlew spotlessApply` before committing, no `*` imports are allowed.
I always run `./gradlew spotlessApply clean build installDist` to make sure all my code has been cleaned up.

2022-01-19 10:13 UTC, quintesse commented on src/main/java/dev/jbang/catalog/CatalogUtil.java
> +	 * @param properties
Could you add some description here?

2022-01-19 10:13 UTC, quintesse commented on src/main/java/dev/jbang/catalog/CatalogUtil.java
> +	 * @param properties
Same here

2022-01-19 10:13 UTC, quintesse commented on src/main/java/dev/jbang/cli/Template.java
> +				if (StringUtils.isNotBlank(entry.getValue().getDescription())) {
Given the changes I suggested for the `TemplatePropertyConverter` I'd simply check for `null` here.

2022-01-19 10:13 UTC, quintesse commented on src/main/java/dev/jbang/catalog/TemplateProperty.java
> +	@SerializedName(value = "default-value")
This is just my personal preference but I'd suggest simply using `default` instead of `default-value`.

2022-01-19 21:34 UTC, nandorholozsnyak commented
Thank you for the feedback @quintesse . Will take a look on these. 
Just a quick feedback, in the Contribution file maybe some code standard and requirements should be visible, I understand I have to write the tests and make sure it is well formatted, but for the formatting issues I do remember I ran the spotless plugin before committing :D I'm just setting up the git hook for it to never happen again.
Is there any proper documentation about the code layering and structure?

2022-01-20 00:29 UTC, quintesse approved these changes
This would already be good enough to merge IMO.
But we need a couple of more tests, especially in `TestTemplate`, just to make sure that the information gets stored and retrieved correctly. A couple of edge cases perhaps (wrongly formatted property, things like that).

2022-01-20 00:33 UTC, quintesse commented
> Is there any proper documentation about the code layering and structure?

Not really, I'd just look at the surrounding code when you add/change things and try to follow that style as much as possible. And if you write something completely new then we tend to just let you write it as you want, as long as it is good code :-)

2022-01-20 00:36 UTC, quintesse commented
> This would already be good enough to merge IMO.

Once it builds and tests correctly of course 😉

2022-01-20 00:41 UTC, maxandersen commented
> > Is there any proper documentation about the code layering and structure?
> 
> 
> 
> Not really, I'd just look at the surrounding code when you add/change things and try to follow that style as much as possible. And if you write something completely new then we tend to just let you write it as you want, as long as it is good code :-)

...and we apply code formatting automatically so the way I code is just whatever I need with whatever formatting my ide uses - Then run the spotlessapply
And it will fix it. Avoids having to think about formatting :)

2022-01-20 00:49 UTC, quintesse commented
> And it will fix it

We should do something about the indenting, though. The fact that it tries to line up with the end of the first line (or whatever it is it tries to do) often creates some pretty horrible indents 😞

2022-01-20 07:56 UTC, nandorholozsnyak commented
I have never used Spotless before but .editorconfig. For me it was working well, of course if you are an Eclipse or Netbeans user you need a plugin for it in the IDE, but it has Gradle plugins as well. 
https://editorconfig.org/

2022-01-20 09:04 UTC, quintesse commented
@nandorholozsnyak Oh, Spotless works well enough, it's just the chosen configuration that I'm somewhat unhappy with :-)

2022-01-23 11:17 UTC, nandorholozsnyak commented
Hey @quintesse I added tests and small changes. I added the CLI docs as well, but I'm not sure if it would be enough or not.

2022-01-24 21:14 UTC, nandorholozsnyak commented
Btw, locally I use Java 17 (Temurin) and the build fails with that, so this is why I was not able to spot what is not working, Spotless is not working with that, or at least some things are not okay with that.
I ran the code you mentioned, now it should be working.

2022-01-24 22:50 UTC, quintesse approved these changes

2022-01-24 22:55 UTC, merged

2022-01-24 22:55 UTC, quintesse commented
Good job @nandorholozsnyak, thanks !

2022-01-26 17:42 UTC, nandorholozsnyak commented
Just a quick question @quintesse , did I just screw up the Codecov reports? I see that the master is failing because of the codecov report, and I just saw your new PR and checked the code as well and saw a lot of "misses" by the codecov. Should I open a PR to fix those?

2022-01-26 23:30 UTC, quintesse commented
Codecov is still in somewhat of an experimental phase for us right now, so don't worry too much about it. At some point we'll want to do something with that information though :-)