fix: Unable to use {basename} in template file-refs
jbangdev/jbang pull request #1319
Opened 2022-03-20 14:50 UTC by nandorholozsnyak

- {filename} and {basename} have different validation rules for their usage
- fixes #1318

2022-03-21 19:30 UTC, nandorholozsnyak commented
Can I ask for a review @quintesse @maxandersen ?

2022-03-21 22:03 UTC, quintesse commented
I added an extra test that shows where your code causes problems. That test should already have existed of course but it didn't :-)

So it's not that we disagree with what you want to do, it's a very useful feature. But the way templates work is honestly a bit obscure. So right now a template needs at least one of these two things to be true:

- there is at least a single entry named `{filename}=somefile.ext[.qute]` and the name given by user to the `init` command should have the same `.ext` extension as the file _after_ the `=` sign
- there is at least a single entry named `{basename}.ext=somefile.someext[.qute]` and the name given by user to the `init` command should have the same `.ext` extension as the file _before_ the `=` sign

Right now JBang does this check for all files in a template, which is not really what you want because it prevents a template author from doing exactly what you want to do.

But we still need to make sure that _at least one file follows one of these rules_!

And right now your code only follows the first rule.

The code would have to be adapted in such a way that it checks that the first file it encounters that matches those rules is enough. So having:

```
{filename}=somefile.java
{basename}.md=somefile.md
```

is correct, but so is:

```
{basename}.java=somefile.java
{basename}.md=somefile.md
```

And in both cases JBang has to check that typing `init myfile.java` is correct and so is `init myfile`, but typing `init myfile.foo` or `init myfile.md` should throw an error.

2022-03-21 22:04 UTC, quintesse requested changes
See comment I left on PR

2022-03-21 22:16 UTC, quintesse commented
Perhaps the best thing to do would be to do is to split this code into two steps: https://github.com/jbangdev/jbang/blob/main/src/main/java/dev/jbang/cli/Init.java#L67-L76

The first step checks if the correct rules are followed and throws an error when it finds a problem. And then the second step would be the current code without the error checking.

2022-03-22 07:30 UTC, nandorholozsnyak commented
Wow.

Thanks for the input, let me dig deeper and find a good solution for this as soon as I have time.

2026-08-23 22:34 UTC, maxandersen commented
replaced with #2646

2026-08-23 22:34 UTC, closed without merging