Catalog command improvements
jbangdev/jbang pull request #1743
Opened 2024-02-02 23:02 UTC by quintesse

fix: properly listing the catalog names (fixes #1678)
feat: added --force options to catalog add commands (related to the above)
feat: added import feature to catalog refs

The last feature is something that we discussed (not sure if there's an issue for it, couldn't find it): an option that imports the items defined in a catalog and makes them available to the user without having to specify the full name, eg. using `@somecatalog`.

Right now this only works for local catalogs, so if you add a catalog with `jbang catalog add --import maxandersen` it will make all aliases, templates and catalog refs in that catalog available to the user without having to specify `@maxandersen`.

NB: The reason for the local catalog limitation (for now?) is to prevent a cascade. Otherwise you could import a catalog that references a bunch of other catalogs and imports them all and suddenly you have a gazillion aliases and templates available. But perhaps this is a restriction that could be relaxed in the future.

Btw, with this feature you could almost implement something like the jbanghub with very little changes. If you import the Hub's catalog and if it would have a list of catalog references, like for example "sqlline", then we would have a simple way to manage "named catalogs". You could do `jbang foo@sqlline` and it would work.

2024-02-03 07:38 UTC, maxandersen commented
functionallity wise looks good. 2 questions:

1) not sure I follow what "only local" means ...got an example of where using remote vs local?

2) the imported catalog still "pollutes" my default catalog names available. I didn't expect that. i.e. I put this in a jbang-catalog:
```
"catalogs": {
    "jbanghubby": {
      "catalog-ref": "https://github.com/jbanghub/jbang-catalog/blob/HEAD/jbang-catalog.json",
      "import": true
    }
  },
```

now `jbang mima` works - great, but `jbang mima@jbanghubby` works too... meaning that added catalogs wether implicit or explicit can "rewire" what catalogs I have on my system...that is not good from a security and predictability wise.

i.e. lets say someone adds this to their public catalog:

```
"catalogs": {
    "jbangdev": {
      "catalog-ref": "https://github.com/jbanghub/jbang-catalog/blob/HEAD/jbang-catalog.json",
      "import": true
    }
  },
```

now `jbang env@jbangdev` is failing but imagine i add a env command that just did some random operation.

This side-effect is not caused by this change but. a problem we have already today and I honestly think we need to fix/break that behavior - at least by default.

2024-02-03 20:16 UTC, quintesse commented
Sure:

1. it only works for catalogs found on your file system, it doesn't work for remote catalogs. Or in other words you _must_ at some point have used an `--import` flag while adding a catalog manually. It's not that you added a catalog and then they decide to add an "import: true" and suddenly you get a whole bunch of extra stuff. (On the other hand, if you _did_ use `--import` on an untrusted catalog they could decide to add a whole bunch of stuff you don't want).
2. "now jbang mima works - great, but jbang mima@jbanghubby works too..", sure, the catalog still has an explicit name, nothing you can do about that. The `--import` just means that you can now _also_ use all the items in the catalog without the fully qualified name.

The overriding... well, yes, that could probably happen. I can think of 2 solutions: make jbangedv/jbanghub special (not my favorite) or prioritize "toplevel" catalogs over "sub" catalogs. That way any catalogs that you explicitly added or used yourself will always have preference.

2024-02-19 17:55 UTC, quintesse commented
I've updated the code to prioritize local catalogs over imported catalog refs. Still need to fix an integration test though.

2024-02-23 21:38 UTC, quintesse commented
@maxandersen this is now in a testable state again. It won't show aliases/templates recursively anymore. And you can now also do things like `jbang catalog add microsoft@jbanghub` (you could do `jbang catalog add --import jbanghub` but then you'd get _all_ catalog refs and perhaps you're only interested in the MS one).

While creating this PR I started wondering if we should actually take into account the catalogs that get added to `implicit-catalog.json`. Right now whenever you do anything like `jbang script@somecatalog` and `somecatalog` is some implicit catalog reference we store it in that file. But what happens is that immediately all the aliases and templates (and catalog refs) in that file start showing up in the `alias list` and `template list` commands. And I've started wondering if that's actually a good idea. It's at least surprising, I think.

2024-02-23 23:00 UTC, maxandersen commented
Totally agree we shouldn't list from implicit catalogs by default.

2024-02-24 12:09 UTC, maxandersen commented
`j! catalog add --import jbanghub` gives me `Unknown option: '--import'` ...

2024-02-24 13:59 UTC, maxandersen commented on src/main/java/dev/jbang/catalog/CatalogRef.java
> +	public final Boolean importItems;
doe that need to be a tri-state Boolean?

2024-02-25 20:28 UTC, quintesse commented
> not sure if this is expecte:
...
> result in duplicated catalog list - one from the first one then the other set.
> 
> `jbang catalog remove jbanghub` remove them all.

Could you try and see if only running `jbang catalog add --import --force jbanghub` gives you the same result? Because then it might be expected. Because the `add` will import the jbanghub "alias", import or not. The import just has the _added_ effect of making its contents available locally as well. That would also explain why "both" disappear after a remove.

> I have ~14 jbang-catalog.json files in the cache.
>
> I'm assuming that is also cause of why jbang catalog list is slow.
>
> Is that expected?

I'll look into it because we definitely don't want that, no.

> does that need to be a tri-state Boolean?

It doesn't _need_ to be, no. I simply tend to like it because it gives us a way to check if the value was actually added by the user or not. But if you prefer I can change it to a simple `boolean`.

2024-02-25 23:07 UTC, maxandersen commented on src/main/java/dev/jbang/catalog/CatalogRef.java
> +	public final Boolean importItems;
if good for deciding if set by user or not its all good.

2024-02-25 23:09 UTC, maxandersen commented
> Could you try and see if only running `jbang catalog add --import --force jbanghub` gives you the same result?

it does ...which seems wrong imo. the duplication is "noise" compared to what --import is supposed to do (make the aliases available)

2024-02-26 23:43 UTC, quintesse commented
@maxandersen this is now in a testable state again. Let me know what you think.

2024-02-29 11:35 UTC, maxandersen commented
jbang catalog remove karatelabs seem to update the cached version so it stays removed until clear cache.

2024-03-05 16:29 UTC, maxandersen commented
@quintesse areyø ypu able to look Into this one or should I just make it error if it tried to edit file in cache?

2024-03-06 00:27 UTC, quintesse commented
> @quintesse areyø ypu able to look Into this one or should I just make it error if it tried to edit file in cache?

Sorry, got side-tracked, I will fix this first thing tomorrow!

2024-03-06 17:00 UTC, quintesse commented
Ok, fixed

2024-03-07 11:58 UTC, maxandersen commented on src/main/java/dev/jbang/catalog/CatalogUtil.java
> +				Util.warnMsg("Unable to remove alias because it is imported from a remote catalog");
```suggestion
				Util.warnMsg("Unable to remove alias " + name + " because it is imported from a remote catalog");
```

2024-03-07 11:59 UTC, maxandersen requested changes
looks good but should be okey to list the name in the exception should it not ?

2024-03-07 12:19 UTC, quintesse commented on src/main/java/dev/jbang/catalog/CatalogUtil.java
> +				Util.warnMsg("Unable to remove alias because it is imported from a remote catalog");
Done

2024-03-07 15:02 UTC, merged