feat: improves jdk command output messages
jbangdev/jbang pull request #350
Opened 2020-09-23 21:13 UTC by abelsromero

Adds more friendly messages for 'jdk list' and 'jdk uninstall' adding
feedback for users.

Fixes #347

2020-09-23 21:53 UTC, maxandersen commented
lookslike you made some linux assumptions in tests :)

2020-09-24 12:38 UTC, abelsromero commented
I honestly out of ideas, I am gonna have to make a VM

2020-09-24 13:34 UTC, abelsromero commented
fixed :partying_face:

2020-09-24 19:25 UTC, maxandersen commented on src/main/java/dev/jbang/cli/Jdk.java
> +	public static void main(String[] args) {
this looks out of place - left over testing/sanity check code ?

2020-09-24 19:26 UTC, maxandersen approved these changes
looks fine now but please look at the "extra" main method

2020-09-24 19:27 UTC, maxandersen requested changes
pressed wrong button :)

2020-09-24 20:47 UTC, maxandersen commented
i've forced pushed with rebase + remove of bad main method. if it pass test i'll merge to hopefully make release.

2020-09-24 22:00 UTC, merged

2020-09-25 06:43 UTC, abelsromero commented
> i've forced pushed with rebase + remove of bad main method. if it pass test i'll merge to hopefully make release

sorry u_U I mistake