docs: Explain wrapper's .jbang/ and suggest to .gitignore it
jbangdev/jbang pull request #505
Opened 2020-11-15 12:48 UTC by vorburger

Just a small first contrib with a minor doc clarification about something I've run into when using jbang in a project.

PS: Hey @maxandersen I'd known about jbang since early days, but only today found a reason to actually play with it - it's so cool!

2020-11-15 20:29 UTC, maxandersen commented on readme.adoc
> +The `./.jbang` directory which `jbang wrapper install` creates is just a cache which you typically would not commit to a source code repository, so you can e.g. `echo .jbang/ >>.gitignore`.
this debatable - the `.jbang/jbang.jar` file is currently the only way we know what version of jbang you installed. we don't have a `.jbang/jbang-wrapper.properties` similar to ` .mvn/wrapper/maven-wrapper.properties` which mvn wrapper uses to know which version of jbang you use.

As is today if you don't commit the .jbang folder you will get the latest downloaded ...which is probably just fine - but just saying that the folder isn't 100% a cache as it encodes that "

so we'll wanna find a different way to phrase it.

2020-11-15 20:30 UTC, maxandersen requested changes
if you can come with an update that doesn't say its "just a cache" I'm good ;)

2020-11-15 20:30 UTC, maxandersen commented
> PS: Hey @maxandersen I'd known about jbang since early days, but only today found a reason to actually play with it - it's so cool!

watch out - it can be addicting! : )

2020-11-22 01:16 UTC, maxandersen commented
actually - as implemented now it is pure cache as if you remove it and jbang is otherwise in path or ~/.jbang/bin it will use that jbang ...okey committing this for now.

2020-11-22 01:16 UTC, merged

2020-11-22 11:54 UTC, quintesse commented
Thing is `./.jbang` can be used for other things as well, like the `jbang-catalog.json` file as well. So we can either update the docs to specifically add `.jbang/jbang.jar` to .gitignore, or put the JAR in a subdirectory, eg. `.jbang/cache` and add that to .gitignore.

2020-11-22 22:48 UTC, maxandersen commented
wanna do a new PR to clarify ? :)