docs: Explain where native binary currently ends up (re. #508)
jbangdev/jbang pull request #509
Opened 2020-11-15 15:37 UTC by vorburger

see #508

This would be updated to document `-o/--output` when that's implemented.

I'll see if I can have a go at that some time.

2020-11-15 15:38 UTC, vorburger commented
This PR has 2 commits because its based on / includes my earlier #507, just to avoid having to resolve a merge conflict when that's in.

2020-11-15 20:36 UTC, maxandersen commented on readme.adoc
> +The built native image binary will be in `~/.jbang/cache/jars/YOUR.java.HASH.jar.bin` (see [#508] for an `-o/--output`).
```suggestion
The built native image binary will be placed in jbang's cache and used on next run.
```

I don't want to make the contents of ~/.jbang/cache "api" ...at leats for now it is to be considered a black box for users.

Definitely ok adding a `-o/--out` to make this possible to get..

2020-11-15 20:37 UTC, maxandersen requested changes
lets see if we can find phrasing not making cache content documented.

2020-11-22 01:12 UTC, maxandersen commented
merging with a hint rather than documenting internal details.

2020-11-22 01:12 UTC, closed without merging