feat: Add runtime options for aliases
jbangdev/jbang pull request #976
Opened 2021-08-08 13:23 UTC by quintesse

Fixes #975

2021-08-12 21:16 UTC, maxandersen commented on src/main/java/dev/jbang/cli/Run.java
> +	@CommandLine.Option(names = { "--catalog" }, description = "path to catalog file")
what is this used for in context of run ?

2021-08-12 21:18 UTC, maxandersen requested changes
looks good but not following why this change means run now has a --catalog option ?

2021-08-12 22:45 UTC, quintesse commented
Ah sorry yes, I added that because the `jbang alias` and `jbang catalog` commands have a `-f`/`--file` option to explicitly specify the catalog file to read/write, but `run` didn't have that so it wasn't possible to tell it to "use this particular catalog file when resolving aliases/catalogs". Which might not seem that useful for everyday use but was essential for testing :-)
I can remove it but then testing possibly becomes somewhat harder, especially because the normal way the `run` command does lookups is pretty complex. So you have to make sure you override all the proper paths so it will read the test file and not some other file on the system.

2021-08-13 10:17 UTC, merged

2021-08-13 10:17 UTC, maxandersen commented
Ack. Makes sense. Merged. Thanks!!